version: '3'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    tty: true
    networks:
     - node-network
    ports:
      - 8080:80
    depends_on:
      - app

  app:
    build:
      context: ./node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 200s node index.js
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - db
  
  db:
    image: mysql:5.7.37
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
 node-network:
  driver: bridge